theme: jekyll-theme-minimal
title: [CATC-TEMPLATES]
description: [This site is set up to help companies adopt better automation practices with Catalyst Center and to help them evolve toward an environment that balances business demand with device configuration.]

exclude:
  - CODE/WORKFLOWS/EXCHANGE/